name: ltreesitter

on:
  schedule:
    - cron: '0 0 1/14 * *'
  push:
    branches: master

jobs:
  ltreesitter-windows:
    name: ltreesitter on Windows
    runs-on: windows-latest
    needs: ltreesitter-linux
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            git
            mingw-w64-x86_64-tree-sitter
            mingw-w64-x86_64-lua
            mingw-w64-x86_64-gcc
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          repository: 'takase1121/ltreesitter'
          ref: lite-xl-plugin-api
      - name: 'Build'
        run: gcc -shared -o ltreesitter.dll -O2 -fPIC -I./include csrc/*.c -l:liblua.a -l:libtree-sitter.a -lm
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ltreesitter-windows
          path: ltreesitter.dll
      - name: Checkout builds repo
        uses: actions/checkout@v3
        with:
          path: builds-repo
      - name: Create Release(s)
        env: { GITHUB_TOKEN: "${{ github.token }}" }
        shell: powershell
        working-directory: builds-repo
        run: gh release upload builds ../*.dll

  ltreesitter-linux:
    name: ltreesitter on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: sudo apt install gcc liblua5.4-0 liblua5.4-dev libtree-sitter0 libtree-sitter-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          repository: 'takase1121/ltreesitter'
          ref: lite-xl-plugin-api
      - name: 'Build'
        run: gcc -shared -o ltreesitter.so -O2 -fPIC -I./include -I/usr/include/lua5.4 csrc/*.c -llua5.4 -l:libtree-sitter.a -lm
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ltreesitter-linux
          path: ltreesitter.so
      - name: Checkout builds repo
        uses: actions/checkout@v3
        with:
          path: builds-repo
      - name: Create Release(s)
        env: { GITHUB_TOKEN: "${{ github.token }}" }
        working-directory: builds-repo
        run: gh release delete -y builds || true; gh release create -p -t 'Builds' builds ../*.so
