name: Treesitter Parsers

on:
  push

jobs:
  build:
    name: Compile Windows parsers
    runs-on: windows-latest
    continue-on-error: true
    strategy:
      matrix:
        parser:
          - tree-sitter/tree-sitter-c
          - the-mikedavis/tree-sitter-diff
          - tree-sitter/tree-sitter-go
          - camdencheek/tree-sitter-go-mod
          - MunifTanjim/tree-sitter-lua
          - tree-sitter/tree-sitter-rust
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          install: >-
            git
            mingw-w64-x86_64-tree-sitter
            mingw-w64-x86_64-gcc
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.parser }}
      - name: 'Build'
        run: 'gcc -o parser.dll -shared src/*.c -Os -I./src -fPIC'
      - name: Parser Name
        env:
          PARSER: ${{ matrix.parser }}
        id: split
        run: echo "::set-output name=fragment::${PARSER##*/}"
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.split.outputs.fragment }}-windows-x86_64
          path: |
            parser.dll
