name: Treesitter Parsers

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Parsers release tag
        default: 'parsers'
        type: string
  push:
    branches: [master]

jobs:
  linux-parsers:
    name: Compile Linux parsers
    runs-on: ubuntu-latest
    container: ghcr.io/lite-xl/lite-xl-build-box:latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Build
        run: |
          ./setup.sh
          make -j$(nproc)
      - uses: actions/upload-artifact@v3
        with:
          name: parsers-linux-x86_64
          path: "*.so"
      - name: Upload to release
        uses: ncipollo/release-action@v1
        with:
          name: 'Treesitter Parsers'
          tag: ${{ inputs.tag || 'parsers' }}
          commit: master
          allowUpdates: true
          artifacts: "*.so"

  windows-parsers:
    name: Compile Windows parsers
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          install: >-
            git
            make
            mingw-w64-x86_64-python
            mingw-w64-x86_64-gcc
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Build
        run: |
          ./setup.sh
          LDFLAGS=-static-libstdc++ make -j$(nproc)
        env:
          SOEXT: dll
      - uses: actions/upload-artifact@v3
        with:
          name: parsers-windows-x86_64
          path: "*.dll"
      - name: Upload to release
        uses: ncipollo/release-action@v1
        with:
          name: 'Treesitter Parsers'
          tag: ${{ inputs.tag || 'parsers' }}
          commit: master
          allowUpdates: true
          artifacts: "*.dll"
