name: Treesitter Parsers

on:
  push

jobs:
  build:
    name: Compile Windows parsers
    runs-on: windows-latest
    continue-on-error: true
    strategy:
      matrix:
        parser:
          - tree-sitter/tree-sitter-go
          - tree-sitter/tree-sitter-lua
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            git
            mingw-w64-x86_64-tree-sitter
            mingw-w64-x86_64-gcc
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.parser }}
      - name: 'Build'
        run: 'gcc -o parser.dll -shared src/*.c -Os -I./src -fPIC'
