name: Treesitter Parsers

on:
  push

jobs:
  create-release:
    name: Make release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - run: gh release delete -y parsers || true; gh release create -p -t 'Treesitter Parsers' parsers
        env: { GITHUB_TOKEN: "${{ github.token }}" }
  
  linux-parsers:
    name: Compile Linux parsers
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        parser:
          - tree-sitter/tree-sitter-c
          - tree-sitter/tree-sitter-cpp
          - the-mikedavis/tree-sitter-diff
          - tree-sitter/tree-sitter-go
          - camdencheek/tree-sitter-go-mod
          - MunifTanjim/tree-sitter-lua
          - tree-sitter/tree-sitter-rust
    steps:
      - name: Get parser name
        env:
          PARSER: ${{ matrix.parser }}
        id: split
        run: echo "parser=${PARSER##*/}" >> $GITHUB_OUTPUT
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Checkout parser sources
        uses: actions/checkout@v3
        with:
          path: ${{ steps.split.outputs.parser }}
          repository: ${{ matrix.parser }}
      - name: Build
        uses: docker://fedora:latest
        with:
          args: >
            sh -c "
            sudo dnf install gcc make wget libtree-sitter libtree-sitter-devel -y &&
            wget -O /usr/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 &&
            chmod +x /usr/bin/yq &&
            chmod +x ./fake-gyp &&
            ./fake-gyp ${{ steps.split.outputs.parser }} > Makefile &&
            make &&
            mv ${{ steps.split.outputs.parser }}/parser.dll ${{ steps.split.outputs.parser }}/parser.so"
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.split.outputs.parser }}-linux-x86_64
          path: |
            ${{ steps.split.outputs.parser }}/parser.so
      - name: Upload to release
        run: gh release upload parsers ${{ steps.split.outputs.parser }}/parser.so
        env: { GITHUB_TOKEN: "${{ github.token }}" }

  windows-parsers:
    name: Compile Windows parsers
    runs-on: windows-latest
    continue-on-error: true
    strategy:
      matrix:
        parser:
          - tree-sitter/tree-sitter-c
          - tree-sitter/tree-sitter-cpp
          - the-mikedavis/tree-sitter-diff
          - tree-sitter/tree-sitter-go
          - camdencheek/tree-sitter-go-mod
          - MunifTanjim/tree-sitter-lua
          - tree-sitter/tree-sitter-rust
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          install: >-
            git
            wget
            make
            mingw-w64-x86_64-tree-sitter
            mingw-w64-x86_64-gcc
      - name: Install yq
        run: wget -O /usr/bin/yq "https://github.com/mikefarah/yq/releases/download/v4.30.8/yq_windows_amd64.exe"
      - name: Get parser name
        env:
          PARSER: ${{ matrix.parser }}
        id: split
        run: echo "parser=${PARSER##*/}" >> $GITHUB_OUTPUT
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Checkout parser sources
        uses: actions/checkout@v3
        with:
          path: ${{ steps.split.outputs.parser }}
          repository: ${{ matrix.parser }}
      - name: Build
        run: |
          ./fake-gyp ${{ steps.split.outputs.parser }} > Makefile
          make
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.split.outputs.parser }}-windows-x86_64
          path: |
            ${{ steps.split.outputs.parser }}/parser.dll
      - name: Upload to release
        run: gh release upload parsers ${{ steps.split.outputs.parser }}/parser.dll
        shell: powershell
        env: { GITHUB_TOKEN: "${{ github.token }}" }
