name: Treesitter Parsers

on:
  push

jobs:
  build:
    name: Compile Windows parsers
    runs-on: windows-latest
    continue-on-error: true
    strategy:
      matrix:
        parser:
          - tree-sitter/tree-sitter-c
          - the-mikedavis/tree-sitter-diff
          - tree-sitter/tree-sitter-go
          - camdencheek/tree-sitter-go-mod
          - MunifTanjim/tree-sitter-lua
          - tree-sitter/tree-sitter-rust
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          install: >-
            git
            wget
            make
            mingw-w64-x86_64-tree-sitter
            mingw-w64-x86_64-gcc
      - name: Install yq
        run: wget -O /usr/bin/yq "https://github.com/mikefarah/yq/releases/download/v4.30.8/yq_windows_amd64.exe"
      - name: Get parser name
        env:
          PARSER: ${{ matrix.parser }}
        id: split
        run: echo "parser=${PARSER##*/}" >> $GITHUB_OUTPUT
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Checkout parser sources
        uses: actions/checkout@v3
        with:
          path: ${{ steps.split.outputs.parser }}
          repository: ${{ matrix.parser }}
      - name: Build
        run: |
          ./fake-gyp ${{ steps.split.outputs.parser }} > Makefile
          make
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.split.outputs.parser }}-windows-x86_64
          path: |
            ${{ steps.split.outputs.parser }}/parser.dll
